id: P008237
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:09:49.412728
source_metadata:
  id: bdr:W22434
  title: ཇོ་ནང་ཁྲིད་བརྒྱ་བརྒྱུད་འདེབས།
  author: ''
  volumes:
    064c5f3486bc42918b837145ed2d8f26:
      image_group_id: I1KG1325
      title: ''
      volume_number: 1
      total_pages: 303
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
